### ISSUE TITLE
console一直处于CrashLoopBackOff状态

### ISSUE THREAD

**Issue by glyslxq** [cubefs/cubefs-helm#15]
把/cfs/logs/ 挂载到持久化目录，也没有生成任何日志

console容器启动日志
{
  "role": "console",
  "logDir": "/cfs/logs/",
  "logLevel": "error",
  "listen": "1602",
  "master_instance": "master-service:17010",
  "objectNodeDomain": "console.chubaofs.com",
  "masterAddr": [
    "master-0.master-service:17010",
    "master-1.master-service:17010",
    "master-2.master-service:17010",
    "master-3.master-service:17010"
  ],
  "monitor_addr": "http://prometheus-service:9090",
  "dashboard_addr": "http://monitor.chubaofs.com",
  "monitor_app": "cfs",
  "monitor_cluster": "my-cluster"
}
start console

**Comment by hoshibara** [comment]
same problem

**Comment by shuoranliu** [comment]
@Huweicai

**Comment by Huweicai** [comment]
I'll have a look.

**Comment by Huweicai** [comment]
The console component is deprecated now, will be removed soon.

**Comment by Huweicai** [comment]
The console component is deprecated now, will be removed soon.
