### ISSUE TITLE
Chart deploys successfully, but PVC aren't really connected to cFS

### ISSUE THREAD

**Issue by OzySky** [cubefs/cubefs-helm#6]
Hi,
I managed to deploy the chart, yet when I apply the PVC to pods and write to it, it's not synced between the pods, and ChubaoFS console shows data partitions and pvc volume, but the disk usage doesn't change at all.

**Comment by chengyu-l** [comment]
The first one may be not a problem, just wait for a moment. The second one need ChubaoFS to check it. @shuoranliu
